### PR TITLE
Updated Navbar Component

### LINKED ISSUE #4: Make the Navbar Sticky.
The navbar currently isn't sticky. Now, it disappears whenever we scroll. Can anyone please make the header sticky so it always stays at the top of the website?

### PR DESCRIPTION
**Pull request by YajanaRao**
Fixes: #4 

- Added fixed navbar class
- Changing background color on scroll

### CODE REVIEW

**Review by burhanharoon — APPROVED** [review]
This is perfect! Your code looks diligent and of the utmost quality. Thanks for the contribution. Happy open-source!

**Comment by burhanharoon** [comment]
Thank you so much @YajanaRao. You're an amazing developer. The website looks very good now. Thanks and best of luck for the future.

**Comment by YajanaRao** [comment]
@burhanharoon Best wishes for your future

**Comment by burhanharoon** [comment]
Thanks mate. Cheers!

**Pull request merged**
