### PR TITLE
made the menu button work when in a small screen

### LINKED ISSUE #8: The mobile navbar doesn't work.
**Current Behaviour:**
The navbar doesn't work on clicking on the hamburger icon in the mobile view.

image

**Expected Behaviour:**
The navbar should open/extend. I have the design. The navbar menu should look like this: 

image

**Note: Please use Tailwind-CSS to accomplish the task (if you can).**

### PR DESCRIPTION
**Pull request by stevenjburrows**
got the menu to open and close on a small screen using tailwind
closed #8

### CODE REVIEW

**Comment by stevenjburrows** [comment]
@burhanharoon I don't have a vercel account to see the error

**Comment by burhanharoon** [comment]
Here you go with the log:

**Comment by stevenjburrows** [comment]
@burhanharoon  thanks, I made a typo and fixed it

**Review by burhanharoon — APPROVED** [review]
Awesome!

**Pull request merged**
