### PR TITLE
Issue12 next js

### PR DESCRIPTION
**Pull request by avezqureshi14**
Pull Request for issue #12 , Completed Successfully

### CODE REVIEW

**Review by burhanharoon — APPROVED** [review]
Awesome!

**Comment by burhanharoon** [comment]
Thank you @avezqureshi14 . Nice job. I wish you the best of luck in the future.

**Comment by avezqureshi14** [comment]
> Thank you @avezqureshi14 . Nice job. I wish you the best of luck in the future.

Thank you @burhanharoon bhaiya

**Comment by burhanharoon** [comment]
Great. Thanks again!

**Pull request merged**
